name: tranquillyzer
channels:
  - conda-forge
  - nvidia
  - bioconda
  - defaults

dependencies:
  - python=3.10.12
  - pandas=2.3.1
  - polars=1.32.3
  - matplotlib=3.10.5
  - seaborn=0.13.2
  - tqdm=4.67.1
  - filelock=3.19.1
  - numba=0.61.2
  - typer=0.16.0
  - rapidfuzz=3.13.0
  - python-Levenshtein=0.27.1
  - minimap2=2.30
  - samtools=1.22.1
  - pip

  # pip-installed packages
  - pip:
      # use NVIDIAâ€™s index for CUDA wheels
      - --extra-index-url https://pypi.nvidia.com
      # packages
      - numpy==1.26.4
      - biopython==1.85
      - pysam==0.23.3
      - bcbio-gff==0.7.1
      - scikit-learn==1.7.1
      - "tensorflow[and-cuda]==2.15.0"
      - "tensorflow-addons==0.22.*"
      - tf2crf==0.1.33
      - psutil==7.0.0
      - pytest==8.4.1
      - pytest-cov==6.2.1
