project:
  type: website

website:
  title: "Tranquillyzer Documentation"
  description: "Documentation site for Tranquillyzer, a deep-learning framework for processing long-read scRNA-seq data"
  page-footer:
    left: "Copyright 2025, The Shen Lab at Van Andel Institute"
    right:
      - icon: github
        href: https://github.com/huishenlab/tranquillyzer
  navbar:
    search: true
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: webpages/install.qmd
        text: Install
      - href: webpages/quick_start.qmd
        text: Quick Start
      - href: webpages/model_training.qmd
        text: Model Training
      - href: webpages/usage.qmd
        text: Usage
      - href: webpages/releases.qmd
        text: Releases
    right:
      - icon: github
        href: https://github.com/huishenlab/tranquillyzer

format:
  html:
    theme: lumen
    highlight-style: solarized
    css: styles.css
    toc: true
    code-copy: true
    code-block-border-left: "#000000"
    code-block-bg: "#F3F3F3"



