project:
  type: website

website:
  title: "Tranquillyzer Documentation"
  description: "Documentation site for Tranquillyzer, a deep-learning framework for processing long-read scRNA-seq data"
  page-footer:
    left: "Copyright 2025, The Shen Lab at Van Andel Institute"
    right:
      - icon: github
        href: https://github.com/huishenlab/tranquillyzer
  navbar:
    search: true
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: webpages/install.qmd
        text: Install
      - href: webpages/quick_start.qmd
        text: Quick Start
      - href: webpages/model_training.qmd
        text: Model Training
      - href: webpages/resource_requirements.qmd
        text: Resource Requirements
      - href: webpages/usage.qmd
        text: Usage
      - href: webpages/releases.qmd
        text: Releases
    right:
      - icon: github
        href: https://github.com/huishenlab/tranquillyzer
  sidebar:
    - title: "Model Training"
      style: "docked"
      contents:
        - text: "Overview"
          href: webpages/model_training.qmd
        - text: "1. Read Simulation"
          href: webpages/model_training/read_simulation.qmd
        - text: "2. Introduce Errors"
          href: webpages/model_training/intro_errors.qmd
        - text: "simulate-data CLI"
          href: webpages/model_training/simulate_data_cli.qmd
        - text: "3./4. Model Training"
          href: webpages/model_training/train_model.qmd
        - text: "train-model CLI"
          href: webpages/model_training/train_model_cli.qmd

format:
  html:
    theme: lumen
    highlight-style: solarized
    css: styles.css
    toc: true
    code-copy: true
    code-block-border-left: "#000000"
    code-block-bg: "#F3F3F3"



